### ISSUE TITLE
Lines have gaps

### ISSUE THREAD

**Issue by arpruss** [martinohanlon/minecraft-turtle#3]
I've seen some gaps in a line. See the attached screenshot (which also includes the code that makes for the gappy line). (For the record, that's running on raspberryjammod, but I hope that doesn't make a difference.)

![fullscreen capture 5152015 94753 am](https://cloud.githubusercontent.com/assets/852659/7655346/73bd625c-fae8-11e4-9696-8abf4190b8d9.jpg)

**Comment by martinohanlon** [comment]
Does it leave the gaps in between the lines or in the middle of lines?

**Comment by arpruss** [comment]
Looks like the middle of the lines to me.

**Comment by martinohanlon** [comment]
In that case we need a better 3d bresenham line algorithm (its the MinecraftDrawing.getLine function).

**Comment by arpruss** [comment]
Yeah. I haven't seen the issue (yet) with the one I use in my Turtle class: https://github.com/arpruss/raspberryjammod/blob/master/python2-scripts/mcpipy/turtle.py
Feel free to use it. It's just a direct Python translation of some public domain C++ code I found.

**Comment by martinohanlon** [comment]
The drawLine function uses the same 3d version of the bresenham line algorithm that is in my turtle code. I believe that the algorithm has the potential to leave gaps but this is considered acceptable because it is fast. I'm going to leave it as it is for the time being.
